[package]
name = "irgen-gui"
version = "0.1.1"
edition = "2024"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
gpui = "0.2.2"
gpui-component = "0.5.0"
calamine = { version = "0.30.0", features = ["dates"] }
polars = {version = "0.50.0", features = ["lazy", "strings", "regex", "string_to_integer", "dtype-array", "range", "serde", "dtype-i128", "timezones", "rank"] }
serde = {version = "1.0.219", features = ["derive"] }
anyhow = "1.0.98"
thiserror = "2.0.12"
serde_json = "1.0.141"
quick-xml = { version = "0.38.1", features = ["serialize"] }
derive_builder = "0.20.2"
# regex = "1.11.1"
rust-embed = "8.7.2"
parking_lot = "0.12"

[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = "0.1"

[package.metadata.bundle]
name = "irgen"
identifier = "com.beribeli.irgen"
icon = ["resources/app-icon.icns"]
